# Surface ELO

In [10]:
import sys
from pathlib import Path

# Regarding Tennis_ML_Project/Notebooks, scr is a sibbling, not a child, 
# so we need to add the parent of Notebooks to the path so that we can import from src

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [11]:
import src
print("src imported correctly:", src)

src imported correctly: <module 'src' from 'c:\\Users\\X421IA\\Desktop\\Learning Projects\\Tennis_ML_Project\\src\\__init__.py'>

### Load and prepare Data

In [12]:
import pandas as pd

matches = pd.read_csv("../Data/processed/matches_with_players_clusters.csv")

#### Create ELO feature

In [13]:
from src.features import compute_surface_elo

matches = compute_surface_elo(matches)
matches.head()

{('Ryan Harrison', 'Hard'): 1470.0486636207368, ('Leonardo Mayer', 'Hard'): 1445.426016868708, ('Jared Donaldson', 'Hard'): 1495.0123918252386, ('Jordan Thompson', 'Hard'): 1693.1542395728288, ('Denis Istomin', 'Hard'): 1360.6990593364492, ('Damir Dzumhur', 'Hard'): 1385.35678203729, ('Alex De Minaur', 'Hard'): 1780.6828353124886, ('Steve Johnson', 'Hard'): 1467.4494762160061, ('Michael Mmoh', 'Hard'): 1585.3505681562986, ('Federico Delbonis', 'Hard'): 1313.5206095314327, ('Mischa Zverev', 'Hard'): 1371.8957456865405, ('John Patrick Smith', 'Hard'): 1420.1530091026648, ('Alexandr Dolgopolov', 'Hard'): 1524.8088281510052, ('Diego Schwartzman', 'Hard'): 1494.0915985662027, ('Horacio Zeballos', 'Hard'): 1470.0245424731256, ('Ernesto Escobedo', 'Hard'): 1416.366469966606, ('Matthew Ebden', 'Hard'): 1488.8079175848507, ('Frances Tiafoe', 'Hard'): 1682.6352895958926, ('Hyeon Chung', 'Hard'): 1557.5850955604824, ('Gilles Muller', 'Hard'): 1431.8504539215473, ('Kyle Edmund', 'Hard'): 1531.030727678635, ('Denis Shapovalov', 'Hard'): 1665.6860066319089, ('John Millman', 'Hard'): 1508.8412750170833, ('Peter Polansky', 'Hard'): 1421.4789424070104, ('Yannick Hanfmann', 'Hard'): 1549.0209121751689, ('Milos Raonic', 'Hard'): 1693.1851201772527, ('Nick Kyrgios', 'Hard'): 1799.1096405070166, ('Grigor Dimitrov', 'Hard'): 1817.4144102256414, ('Borna Coric', 'Hard'): 1563.6788511511552, ('Pablo Carreno Busta', 'Hard'): 1651.1794159408332, ('Nikoloz Basilashvili', 'Hard'): 1422.2134313061615, ('Thomas Fabbiano', 'Hard'): 1370.0225461198365, ('Andrey Rublev', 'Hard'): 1683.9156888814703, ('Cedrik Marcel Stebe', 'Hard'): 1468.4733675103184, ('Fernando Verdasco', 'Hard'): 1420.640085608222, ('Dudi Sela', 'Hard'): 1477.345909672918, ('Guido Pella', 'Hard'): 1485.0831666630263, ('Albert Ramos', 'Hard'): 1363.2481041433568, ('Stefano Travaglia', 'Hard'): 1468.4863834015948, ('Jabor Al Mutawa', 'Hard'): 1484.0, ('Mirza Basic', 'Hard'): 1424.9082827635457, ('Andreas Haider Maurer', 'Hard'): 1452.7973334798912, ('Feliciano Lopez', 'Hard'): 1419.7883426132103, ('Guillermo Garcia Lopez', 'Hard'): 1434.6257282953802, ('Peter Gojowczyk', 'Hard'): 1450.582771619139, ('Filip Krajinovic', 'Hard'): 1521.9025632659936, ('Matteo Berrettini', 'Hard'): 1684.1119688799922, ('Viktor Troicki', 'Hard'): 1403.8407806839427, ('Gael Monfils', 'Hard'): 1712.0226443713816, ('Paolo Lorenzi', 'Hard'): 1472.1575074036193, ('Jan Lennard Struff', 'Hard'): 1544.7951213970816, ('Tomas Berdych', 'Hard'): 1580.0552263320433, ('Richard Gasquet', 'Hard'): 1487.592218658776, ('Victor Estrella', 'Hard'): 1423.7296240047965, ('Stefanos Tsitsipas', 'Hard'): 1709.8351503092947, ('Florian Mayer', 'Hard'): 1431.827361369174, ('Aljaz Bedene', 'Hard'): 1496.5735382084392, ('Malek Jaziri', 'Hard'): 1413.4673405449103, ('Dominic Thiem', 'Hard'): 1569.0934399070063, ('Evgeny Donskoy', 'Hard'): 1388.4957095011816, ('Thiago Monteiro', 'Hard'): 1463.8297336467488, ('Ruben Bemelmans', 'Hard'): 1383.5491748084464, ('Laslo Djere', 'Hard'): 1577.5538479154584, ('Marius Copil', 'Hard'): 1491.7957428369727, ('Mikhail Kukushkin', 'Hard'): 1427.7248509236222, ('Radu Albot', 'Hard'): 1507.3174882197643, ('Marton Fucsovics', 'Hard'): 1543.4748754702443, ('Nicolas Kicker', 'Hard'): 1506.6766450745658, ('Nicolas Jarry', 'Hard'): 1527.361223241523, ('Pablo Andujar', 'Hard'): 1433.0226589380102, ('Robin Haase', 'Hard'): 1498.1151006064908, ('Blaz Kavcic', 'Hard'): 1426.6305581000568, ('Ricardo Ojeda Lara', 'Hard'): 1515.9660918698307, ('Jiri Vesely', 'Hard'): 1519.6066158441731, ('Ilya Ivashka', 'Hard'): 1558.9886378667466, ('Sumit Nagal', 'Hard'): 1409.5719713786527, ('Gilles Simon', 'Hard'): 1533.6392686460083, ('Tennys Sandgren', 'Hard'): 1379.973338916259, ('Pierre Hugues Herbert', 'Hard'): 1543.9753987393278, ('Marco Cecchinato', 'Hard'): 1313.668705307553, ('Yuki Bhambri', 'Hard'): 1438.320224284622, ('Arjun Kadhe', 'Hard'): 1436.4586326795566, ('Ramkumar Ramanathan', 'Hard'): 1301.0557497542075, ('Roberto Carballes Baena', 'Hard'): 1506.5692414382765, ('Kevin Anderson', 'Hard'): 1491.2511653983472, ('Benoit Paire', 'Hard'): 1414.1774835383253, ('Roberto Bautista Agut', 'Hard'): 1627.5556508151992, ('Marin Cilic', 'Hard'): 1572.4345647320927, ('Rogerio Dutra Silva', 'Hard'): 1457.2331957012846, ('Karen Khachanov', 'Hard'): 1757.5405840307844, ('Yuichi Sugita', 'Hard'): 1411.788316706643, ('Pablo Cuevas', 'Hard'): 1436.3524481529823, ('Taro Daniel', 'Hard'): 1476.1369485929338, ('Joao Sousa', 'Hard'): 1476.1994141127545, ('Donald Young', 'Hard'): 1399.8299064143189, ('David Ferrer', 'Hard'): 1508.7568687886067, ('Yibing Wu', 'Hard'): 1578.1852919126966, ('Michael Venus', 'Hard'): 1450.168632990468, ('Liam Caruana', 'Hard'): 1441.8794286694238, ('Lukas Lacko', 'Hard'): 1397.6889831653948, ('Casper Ruud', 'Hard'): 1642.9448888635802, ('Tim Smyczek', 'Hard'): 1429.4586121144123, ('Juan Martin del Potro', 'Hard'): 1729.0761450554041, ('John Isner', 'Hard'): 1534.6353216085715, ('Sam Querrey', 'Hard'): 1406.9383065344907, ('Jack Sock', 'Hard'): 1479.9038244421001, ('Alexei Popyrin', 'Hard'): 1718.9751555498544, ('Aleksandar Vukic', 'Hard'): 1546.2079602617605, ('Adrian Mannarino', 'Hard'): 1565.6560857315503, ('Ricardas Berankis', 'Hard'): 1585.8849438563564, ('Alex Bolt', 'Hard'): 1493.8589701946798, ('Daniil Medvedev', 'Hard'): 1857.0511580948476, ('Philipp Kohlschreiber', 'Hard'): 1501.3294315586315, ('Fabio Fognini', 'Hard'): 1446.5734586120254, ('Rafael Nadal', 'Hard'): 1760.7539275747, ('Dusan Lajovic', 'Hard'): 1504.8619866613901, ('Quentin Halys', 'Hard'): 1483.6678051713561, ('Jason Kubler', 'Hard'): 1490.9537967333797, ('Salvatore Caruso', 'Hard'): 1433.7937152485622, ('Mikhail Youzhny', 'Hard'): 1438.7577968990688, ('Dustin Brown', 'Hard'): 1468.736306793522, ('Vasek Pospisil', 'Hard'): 1551.466059243212, ('Dennis Novak', 'Hard'): 1397.1284138651488, ('Mackenzie Mcdonald', 'Hard'): 1580.5392088102044, ('Elias Ymer', 'Hard'): 1515.5691484342585, ('Marcos Baghdatis', 'Hard'): 1503.9587072400589, ('Jo-Wilfried Tsonga', 'Hard'): 1533.927800715717, ('Kevin King', 'Hard'): 1473.7749492318046, ('Gerald Melzer', 'Hard'): 1468.1621632654897, ('Lucas Pouille', 'Hard'): 1517.8179277667737, ('Yoshihito Nishioka', 'Hard'): 1599.1445810225543, ('Andreas Seppi', 'Hard'): 1444.7453242693555, ('Corentin Moutet', 'Hard'): 1496.5194000336162, ('Ivo Karlovic', 'Hard'): 1415.3992713292853, ('Denis Kudla', 'Hard'): 1428.5880514246069, ('Vaclav Safranek', 'Hard'): 1484.0029826707998, ('Maximilian Marterer', 'Hard'): 1430.2445504780505, ('Jeremy Chardy', 'Hard'): 1650.6265173055515, ('Stan Wawrinka', 'Hard'): 1579.5790331245246, ('Novak Djokovic', 'Hard'): 2031.9383799687262, ('Jaume Munar', 'Hard'): 1360.6230429293262, ('Thanasi Kokkinakis', 'Hard'): 1637.9647531082162, ('Alexander Zverev', 'Hard'): 1886.736033892495, ('David Goffin', 'Hard'): 1652.3895662871282, ('Matthias Bachinger', 'Hard'): 1520.0257601397407, ('Julien Benneteau', 'Hard'): 1478.9879571124256, ('Lorenzo Sonego', 'Hard'): 1545.057634270719, ('Soon Woo Kwon', 'Hard'): 1527.599952158562, ('Roger Federer', 'Hard'): 1849.244053458707, ('Gerald Melzer', 'Clay'): 1468.648675002405, ('Ilya Ivashka', 'Clay'): 1469.9831016130706, ('Dominic Thiem', 'Clay'): 1538.3487068801956, ('Dzmitry Zhyrmont', 'Clay'): 1484.0, ('Dennis Novak', 'Clay'): 1449.255592451118, ('Yaraslav Shyla', 'Clay'): 1484.0, ('Nicolas Jarry', 'Clay'): 1636.2625694115322, ('Ivan Endara', 'Clay'): 1484.0, ('Roberto Quiroz', 'Clay'): 1500.736306793522, ('Gonzalo Lama', 'Clay'): 1449.731504207204, ('Jose Rubin Statham', 'Hard'): 1502.3657779569487, ('Di Wu', 'Hard'): 1461.2489485254366, ('Ze Zhang', 'Hard'): 1478.7750850689226, ('Daniel Elahi Galan', 'Hard'): 1434.1439935721285, ('Haydn Lewis', 'Hard'): 1466.1772573492133, ('Alejandro Gonzalez', 'Hard'): 1514.0189038919266, ('Darian King', 'Hard'): 1511.9071899954072, ('Cristian Rodriguez', 'Hard'): 1516.0, ('Xavier Lawrence', 'Hard'): 1484.0, ('Jose Hernandez', 'Hard'): 1531.9676533902368, ('Joao Pedro Sorgi', 'Hard'): 1484.7348170251005, ('Roberto Cid', 'Hard'): 1470.1685892019034, ('Aisam Ul Haq Qureshi', 'Grass'): 1514.9976702823178, ('Soon Woo Kwon', 'Grass'): 1484.9723294008672, ('Aqeel Khan', 'Grass'): 1521.973570713263, ('Seong Chan Hong', 'Grass'): 1484.0, ('M Abid Ali Khan Akbar', 'Grass'): 1516.0, ('Minjong Park', 'Grass'): 1484.0, ('Lloyd Harris', 'Hard'): 1514.3737321775936, ('Edan Leshem', 'Hard'): 1457.1375532108052, ('Nicolaas Scholtz', 'Hard'): 1466.7226142457855, ('Mikael Ymer', 'Hard'): 1589.3858958279664, ('Sergiy Stakhovsky', 'Hard'): 1461.096377711436, ('Artem Smirnov', 'Hard'): 1468.766810297684, ('Borna Coric', 'Clay'): 1560.8252595885979, ('Vasek Pospisil', 'Clay'): 1463.6093867328866, ('Denis Shapovalov', 'Clay'): 1579.8187685327227, ('Viktor Galovic', 'Clay'): 1487.655733601822, ('Thiemo De Bakker', 'Hard'): 1488.5252834609366, ('Albert Ramos', 'Clay'): 1493.9301134076536, ('Liam Broady', 'Clay'): 1458.5486978602162, ('Cameron Norrie', 'Clay'): 1660.1974406007187, ('Roberto Bautista Agut', 'Clay'): 1569.9752203132923, ('Attila Balazs', 'Hard'): 1432.003780930007, ('Zsombor Piros', 'Hard'): 1547.749805836374, ('Julien Cagnina', 'Hard'): 1484.0, ('Dmitry Popko', 'Hard'): 1486.1117235613613, ('Henri Laaksonen', 'Hard'): 1407.3222201334036, ('Adrian Bodmer', 'Hard'): 1469.4680317999093, ('Marc Andrea Huesler', 'Hard'): 1503.9231792679059, ('Roman Hassanov', 'Hard'): 1484.0, ('Sam Querrey', 'Clay'): 1475.482189997568, ('Laslo Djere', 'Clay'): 1560.840721407489, ('John Isner', 'Clay'): 1581.1285894367404, ('Dusan Lajovic', 'Clay'): 1589.8106205288382, ('Pedja Krstin', 'Clay'): 1513.1105460969648, ('Steve Johnson', 'Clay'): 1500.0254891225447, ('Duilio Beretta', 'Clay'): 1516.0, ('Hugo Dellien', 'Clay'): 1432.0242212446715, ('Juan Pablo Varillas', 'Clay'): 1540.4686691071624, ('Federico Zeballos', 'Clay'): 1468.1830207459084, ('Jorge Brian Panta Herreros', 'Clay'): 1516.0, ('Alejandro Mendoza', 'Clay'): 1484.0, ('Luis Diego Chavez Villalpando', 'Clay'): 1516.0, ('Mauricio Echazu', 'Clay'): 1484.0, ('Mohamed Safwat', 'Hard'): 1440.4864336658823, ('Simen Sunde Bratholm', 'Hard'): 1484.0, ('Karim Mohamed Maamoun', 'Hard'): 1515.0137066741656, ('Viktor Durasovic', 'Hard'): 1422.6342557101482, ('Youssef Hossam', 'Hard'): 1513.8278203282016, ('Peter August Anker', 'Hard'): 1484.0, ('Alberto Emmanuel Alvarado Larin', 'Hard'): 1452.9096494429734, ('Marcelo Arevalo', 'Hard'): 1583.3899680657157, ('Martin Cuevas', 'Hard'): 1451.9374414278213, ('Rodrigo Arus', 'Hard'): 1516.0, ('Rafael Eduardo Gonzalez Retana', 'Hard'): 1484.0, ('Laurynas Grigelis', 'Hard'): 1465.1076211154696, ('Jurgen Zopp', 'Hard'): 1469.4064243463295, ('Kenneth Raisma', 'Hard'): 1483.262206751386, ('Ainius Sabaliauskas', 'Hard'): 1500.0338330211207, ('Lamine Ouahab', 'Clay'): 1536.9145878221746, ('George Tsivadze', 'Clay'): 1473.082429244857, ('Amine Ahouda', 'Clay'): 1484.4198595358246, ('Nikoloz Basilashvili', 'Clay'): 1489.6981016541101, ('Anthony Jackie Tang', 'Hard'): 1516.0, ('Shahin Khaledan', 'Hard'): 1484.0, ('Hong Kit Jack Wong', 'Hard'): 1502.8712802290452, ('Mohsen Hossein Zade', 'Hard'): 1484.0, ('Skyler Butts', 'Hard'): 1516.0, ('Amir Hossein Badi', 'Hard'): 1484.0, ('Frederik Nielsen', 'Hard'): 1528.5410171252508, ('Simon Carr', 'Hard'): 1469.1362338285558, ('Peter Bothwell', 'Hard'): 1500.0, ('Soren Hess Olesen', 'Hard'): 1500.0, ('Benjamin Hassan', 'Hard'): 1494.9501843444548, ('Cheng Yu Yu', 'Hard'): 1484.0, ('Hady Habib', 'Hard'): 1585.121027320809, ('Kuan Yi Lee', 'Hard'): 1484.0, ('Chun Hsin Tseng', 'Hard'): 1366.4733948573594, ('Michel Saade', 'Hard'): 1484.0, ('Ti Chen', 'Hard'): 1516.0, ('Jad Ballout', 'Hard'): 1484.0, ('Alberto Lim', 'Hard'): 1514.750238845235, ('Muhammad Althaf Dhaifullah', 'Hard'): 1484.0, ('David Agung Susanto', 'Hard'): 1500.736306793522, ('Jeson Patrombon', 'Hard'): 1467.4854366859615, ('John Bryan Decasa Otico', 'Hard'): 1531.263693206478, ('Anthony Susanto', 'Hard'): 1454.6122883143782, ('Manuel Sanchez', 'Hard'): 1531.263693206478, ('Ignacio Garcia', 'Hard'): 1442.2834200531383, ('Luis Patino', 'Hard'): 1510.5956225442285, ('Alex Diaz', 'Hard'): 1484.0, ('Sebastian Arcila', 'Hard'): 1484.736306793522, ('Ugo Nastasi', 'Hard'): 1498.7451386332903, ('Nicolae Frunza', 'Hard'): 1484.0, ('Christophe Tholl', 'Hard'): 1467.4816970178417, ('Bogdan Borza', 'Hard'): 1515.2032728960862, ('Hubert Hurkacz', 'Hard'): 1728.4648454628632, ('Kamil Majchrzak', 'Hard'): 1553.7599761466913, ('Blaz Rola', 'Hard'): 1471.0179209461326, ('Tom Kocevar Desman', 'Hard'): 1483.1993284863252, ('Sharmal Dissanayake', 'Clay'): 1498.5641271217237, ('Jirat Navasirisomboon', 'Clay'): 1470.1965245402773, ('Wishaya Trongcharoenchaikul', 'Clay'): 1537.0492457159255, ('Yasitha De Silva', 'Clay'): 1453.4695015289756, ('Alex Fairbanks', 'Clay'): 1484.736306793522, ('Harri Heliovaara', 'Hard'): 1480.7860855396102, ('Emil Ruusuvuori', 'Hard'): 1661.6286617140372, ('Aziz Dougaz', 'Hard'): 1511.8371889529938, ('Moez Echargui', 'Hard'): 1498.4792394663375, ('Benjamin Lock', 'Hard'): 1524.9437951098557, ('Altug Celikbilek', 'Hard'): 1577.8421473983522, ('Takanyi Garanganga', 'Hard'): 1450.305505025155, ('Cem Ilkel', 'Hard'): 1453.9938477234507, ('Sarp Agabigun', 'Hard'): 1516.0, ('Mehluli Don Ayanda Sibanda', 'Hard'): 1454.1721796717984, ('Ricardo Rodriguez', 'Hard'): 1515.263693206478, ('Wilfredo Gonzalez', 'Hard'): 1482.217725422013, ('Christopher Diaz Figueroa', 'Hard'): 1500.0, ('Jordi Munoz Abreu', 'Hard'): 1468.736306793522, ('Carlos Taberner', 'Hard'): 1481.7743530821651, ('Norbert Gombos', 'Hard'): 1404.8191635184714, ('Nicolas Mahut', 'Hard'): 1463.9033244181421, ('Kenny De Schepper', 'Hard'): 1468.0891369891426, ('Calvin Hemery', 'Hard'): 1451.0584879552675, ('Yannick Maden', 'Hard'): 1452.8929817836492, ('Yannick Hanfmann', 'Clay'): 1585.053509960956, ('Marco Cecchinato', 'Clay'): 1521.5151808839926, ('Victor Estrella', 'Clay'): 1468.0088625283581, ('Thomaz Bellucci', 'Clay'): 1431.0908111394417, ('Casper Ruud', 'Clay'): 1831.1760634702507, ('Carlos Berlocq', 'Clay'): 1419.790127850922, ('Alessandro Giannessi', 'Clay'): 1453.8470797478583, ('Peter Polansky', 'Clay'): 1468.6409008902265, ('Thiago Monteiro', 'Clay'): 1578.432998946823, ('Horacio Zeballos', 'Clay'): 1490.691749834661, ('Facundo Bagnis', 'Clay'): 1502.2837440752369, ('Stefano Travaglia', 'Clay'): 1424.0292057497727, ('Pablo Andujar', 'Clay'): 1457.2702656255433, ('Roberto Carballes Baena', 'Clay'): 1583.9517779738676, ('Federico Gaio', 'Clay'): 1454.022444975918, ('Ivo Karlovic', 'Clay'): 1458.3442959839083, ('Ernesto Escobedo', 'Clay'): 1431.8786173707433, ('Corentin Moutet', 'Clay'): 1529.8191004175028, ('Adrian Menendez Maceiras', 'Clay'): 1474.775847241099, ('Andrej Martin', 'Clay'): 1472.1224319333812, ('Rogerio Dutra Silva', 'Clay'): 1436.0327240216125, ('Gael Monfils', 'Clay'): 1465.0977950192562, ('Paolo Lorenzi', 'Clay'): 1376.4593195230905, ('Pablo Carreno Busta', 'Clay'): 1644.9091047628986, ('Jozef Kovalik', 'Hard'): 1424.5716443277283, ('Dimitar Kuzmanov', 'Hard'): 1474.7625576658736, ('Ernests Gulbis', 'Hard'): 1490.1575257418526, ('Adrian Andreev', 'Hard'): 1445.2110901812819, ('Martin Klizan', 'Hard'): 1450.9768213842085, ('Alexander Donski', 'Hard'): 1500.736306793522, ('Guillermo Garcia Lopez', 'Clay'): 1454.144301174726, ('Federico Delbonis', 'Clay'): 1517.3005314570887, ('Florian Mayer', 'Clay'): 1417.587614468697, ('Gastao Elias', 'Clay'): 1471.6104675370818, ('Aljaz Bedene', 'Clay'): 1549.483151149414, ('Jiri Vesely', 'Clay'): 1423.7391894282796, ('Pedro Cachin', 'Clay'): 1475.9832983830368, ('Diego Schwartzman', 'Clay'): 1496.2900519391499, ('Andreas Haider Maurer', 'Clay'): 1415.0822067628715, ('Pablo Cuevas', 'Clay'): 1512.1682940901312, ('Leonardo Mayer', 'Clay'): 1432.4996101582944, ('Fernando Verdasco', 'Clay'): 1451.3911156876927, ('Guido Pella', 'Clay'): 1466.568184058424, ('Nicolas Kicker', 'Clay'): 1420.175510979419, ('Fabio Fognini', 'Clay'): 1578.5743121481728, ('Adrian Menendez Maceiras', 'Hard'): 1470.240521924119, ('Kei Nishikori', 'Hard'): 1657.691818375912, ('Noah Rubin', 'Hard'): 1458.5486590048818, ('Bjorn Fratangelo', 'Hard'): 1479.0144624673908, ('Sebastian Korda', 'Hard'): 1755.5579283064787, ('Felix Auger Aliassime', 'Hard'): 1637.7554352983145, ('Tallon Griekspoor', 'Hard'): 1663.6673776040373, ('Franko Skugor', 'Hard'): 1495.3599491113396, ('Alexander Bublik', 'Hard'): 1565.407546655843, ('Cameron Norrie', 'Hard'): 1626.6830491431028, ('Taylor Fritz', 'Hard'): 1852.5307421420828, ('Reilly Opelka', 'Hard'): 1586.7879397613845, ('Hugo Gaston', 'Hard'): 1457.1072801584012, ('Tennys Sandgren', 'Clay'): 1418.9528164341234, ('Marin Cilic', 'Clay'): 1618.9379976583477, ('Lucas Gomez', 'Hard'): 1454.5699710254867, ('Gleb Sakharov', 'Hard'): 1463.4793542779714, ('Joao Domingues', 'Clay'): 1488.3723158390565, ('Renzo Olivo', 'Clay'): 1486.9251835443354, ('Sebastian Ofner', 'Clay'): 1491.0343090771278, ('Thiago Seyboth Wild', 'Clay'): 1525.485781856713, ('Guilherme Clezar', 'Clay'): 1500.999237875167, ('Bradley Klahn', 'Hard'): 1400.5732322772842, ('Evan King', 'Hard'): 1484.442132992747, ('Mitchell Krueger', 'Hard'): 1443.3424978145767, ('Christopher Eubanks', 'Hard'): 1508.1846188693096, ('Liam Broady', 'Hard'): 1519.9750865514093, ('Nicola Kuhn', 'Hard'): 1483.8516594117223, ('Miomir Kecmanovic', 'Hard'): 1562.482688198656, ('Cristian Garin', 'Clay'): 1592.2025917561803, ('Sebastian Ofner', 'Hard'): 1550.930237186024, ('Jurgen Melzer', 'Hard'): 1525.764296481495, ('Damir Dzumhur', 'Clay'): 1500.1656542357787, ('Norbert Gombos', 'Clay'): 1519.9539558779293, ('Martin Klizan', 'Clay'): 1509.8287388174804, ('Mirza Basic', 'Clay'): 1456.8881358839305, ('Jozef Kovalik', 'Clay'): 1513.5316231244099, ('Santiago Giraldo', 'Hard'): 1448.477560448684, ('Guilherme Clezar', 'Hard'): 1484.736306793522, ('Edan Leshem', 'Clay'): 1497.8726041640364, ('Adam Pavlasek', 'Clay'): 1517.0830792057786, ('Dudi Sela', 'Clay'): 1468.0, ('Yshai Oliel', 'Clay'): 1516.0, ('Vaclav Safranek', 'Clay'): 1484.0, ('Prajnesh Gunneswaran', 'Hard'): 1406.8037541136907, ('Denis Istomin', 'Grass'): 1490.4354543900486, ('Sanjar Fayziev', 'Grass'): 1484.736306793522, ('Khumoun Sultanov', 'Grass'): 1516.0, ('Muzammil Murtaza', 'Grass'): 1468.736306793522, ('Gastao Elias', 'Hard'): 1438.2919832213295, ('Alexander Zverev', 'Clay'): 1852.956565357913, ('David Ferrer', 'Clay'): 1492.333273713721, ('Rafael Nadal', 'Clay'): 1842.5761909087928, ('Philipp Kohlschreiber', 'Clay'): 1490.9887302925501, ('Lucas Pouille', 'Clay'): 1404.049695378637, ('Andreas Seppi', 'Clay'): 1385.3087635085865, ('Jeremy Chardy', 'Clay'): 1483.390676540839, ('Dmitry Popko', 'Clay'): 1470.01641908449, ('Mikhail Kukushkin', 'Clay'): 1388.8532750996094, ('Joris De Loore', 'Hard'): 1470.2596468071415, ('Christoffer Konigsfeldt', 'Hard'): 1484.736306793522, ('Holger Rune', 'Hard'): 1775.6071503266094, ('Chun Hun Wong', 'Hard'): 1470.8995525732876, ('Gerardo Lopez Villasenor', 'Hard'): 1485.849413580543, ('Juan Pablo Varillas', 'Hard'): 1419.2895732095315, ('Nicolas Alvarez', 'Hard'): 1515.8785590249765, ('Michal Przysiezny', 'Hard'): 1484.736306793522, ('Daniel Michalski', 'Hard'): 1473.5606585323808, ('Mark Chigaazira', 'Hard'): 1484.0, ('Amine Ahouda', 'Hard'): 1484.5946501227354, ('Adrian Ungur', 'Hard'): 1516.0, ('Lamine Ouahab', 'Hard'): 1484.0, ('Dragos Dima', 'Hard'): 1530.3747137438716, ('Soufiane El Mesbahi', 'Hard'): 1484.0, ('Edris Fetisleam', 'Hard'): 1516.0, ('Yassir Kilani', 'Hard'): 1484.0, ('Jeson Patrombon', 'Clay'): 1479.218475192588, ('John Bryan Decasa Otico', 'Clay'): 1470.1061831420425, ('Palaphoom Kovapitukted', 'Clay'): 1515.3296897362338, ('David Souto', 'Clay'): 1485.0258934533117, ('Ricardo Rodriguez', 'Clay'): 1500.978834769486, ('Martin Cuevas', 'Clay'): 1470.3907499539205, ('Francisco Llanes', 'Clay'): 1499.2000097301343, ('Brandon Perez', 'Clay'): 1484.0, ('Stefan Kozlov', 'Clay'): 1484.877108

,year,tourney_date,surface,tourney_level,winner_id,winner_name,winner_rank,winner_age,winner_ht,loser_id,...,w_bpSaved,w_bpFaced,l_ace,l_df,l_bpSaved,l_bpFaced,winner_cluster,loser_cluster,surface_elo_winner,surface_elo_loser
0,2018,20180101,Hard,A,105992,Ryan Harrison,47.0,25.6,185.0,104919,...,8.0,9.0,10.0,3.0,1.0,4.0,4,4,1500.0,1500.0
1,2018,20180101,Hard,A,111577,Jared Donaldson,54.0,21.2,188.0,111442,...,4.0,5.0,3.0,5.0,7.0,11.0,4,3,1500.0,1500.0
2,2018,20180101,Hard,A,104797,Denis Istomin,63.0,31.3,185.0,106000,...,9.0,11.0,8.0,6.0,10.0,16.0,1,3,1500.0,1500.0
3,2018,20180101,Hard,A,200282,Alex De Minaur,208.0,18.8,183.0,105449,...,2.0,3.0,6.0,2.0,4.0,6.0,0,4,1500.0,1500.0
4,2018,20180101,Hard,A,111581,Michael Mmoh,175.0,19.9,188.0,105643,...,3.0,3.0,4.0,0.0,0.0,2.0,4,1,1500.0,1500.0

In [17]:
# Let's check the ELO ratings for Alexander Zverev in the matches dataset
zverev_elo = matches[(matches["winner_name"] == "Alexander Zverev") | (matches["loser_name"] == "Alexander Zverev")]
zverev_elo[["winner_name", "loser_name", "surface", "surface_elo_winner", "surface_elo_loser"]].head(19)

,winner_name,loser_name,surface,surface_elo_winner,surface_elo_loser
186,Alexander Zverev,Thomas Fabbiano,Hard,1500.000000,1484.000000
226,Alexander Zverev,Peter Gojowczyk,Hard,1515.263693,1545.164684
246,Hyeon Chung,Alexander Zverev,Hard,1548.066068,1532.637295
294,Alexander Zverev,Alex De Minaur,Hard,1517.347350,1552.596433
296,Alexander Zverev,Nick Kyrgios,Hard,1534.965083,1597.217843
524,Alexander Zverev,David Ferrer,Hard,1553.801638,1499.943859
534,Andreas Seppi,Alexander Zverev,Hard,1527.387022,1567.341073
633,Alexander Zverev,Mackenzie Mcdonald,Hard,1549.509189,1483.994065
649,Alexander Zverev,Peter Gojowczyk,Hard,1562.527365,1576.094466
657,Alexander Zverev,Ryan Harrison,Hard,1579.151836,1560.037621
661,Juan Martin del Potro,Alexander Zverev,Hard,1582.261103,1594.272480
762,Joao Sousa,Alexander Zverev,Hard,1472.448485,1577.719556
872,Alexander Zverev,Daniil Medvedev,Hard,1557.014747,1583.001725
892,Alexander Zverev,David Ferrer,Hard,1574.209265,1516.854697
902,Alexander Zverev,Nick Kyrgios,Hard,1587.591723,1605.815418
907,Alexander Zverev,Borna Coric,Hard,1604.430187,1627.416400
910,Alexander Zverev,Pablo Carreno Busta,Hard,1621.487199,1604.905458
911,John Isner,Alexander Zverev,Hard,1540.352284,1636.724161
942,Alexander Zverev,David Ferrer,Clay,1500.000000,1500.000000

#### Build Dataset

In [19]:
def build_match_dataset_with_surface_elo(matches):
    rows = []

    for _, row in matches.iterrows():
        # winner vs loser
        rows.append({
            "year": row["year"],
            "rank_diff": row["winner_rank"] - row["loser_rank"],
            "age_diff": row["winner_age"] - row["loser_age"],
            "height_diff": row["winner_ht"] - row["loser_ht"],
            "cluster_diff": row["winner_cluster"] - row["loser_cluster"],
            "elo_diff": row["surface_elo_winner"] - row["surface_elo_loser"],
            "surface": row["surface"],
            "tourney_level": row["tourney_level"],
            "target": 1
        })

        # loser vs winner
        rows.append({
            "year": row["year"],  # we keep year
            "rank_diff": row["loser_rank"] - row["winner_rank"],
            "age_diff": row["loser_age"] - row["winner_age"],
            "height_diff": row["loser_ht"] - row["winner_ht"],
            "cluster_diff": row["loser_cluster"] - row["winner_cluster"],
            "elo_diff": row["surface_elo_loser"] - row["surface_elo_winner"],
            "surface": row["surface"],
            "tourney_level": row["tourney_level"],
            "target": 0
        })

    return pd.DataFrame(rows)

dataset = build_match_dataset_with_surface_elo(matches)
dataset.head()

,year,rank_diff,age_diff,height_diff,cluster_diff,elo_diff,surface,tourney_level,target
0,2018,-5.0,-5.0,-3.0,0,0.0,Hard,A,1
1,2018,5.0,5.0,3.0,0,0.0,Hard,A,0
2,2018,-40.0,-2.5,5.0,1,0.0,Hard,A,1
3,2018,40.0,2.5,-5.0,-1,0.0,Hard,A,0
4,2018,33.0,5.7,10.0,-2,0.0,Hard,A,1

#### Temporal Split

In [20]:
train_data = dataset[dataset["year"] <= 2022]
val_data = dataset[dataset["year"] == 2023]
test_data = dataset[dataset["year"] > 2023]

#### Imputation

In [21]:
from sklearn.impute import SimpleImputer

numeric_features = ["rank_diff", "age_diff", "height_diff", "cluster_diff", "elo_diff"]

num_imputer = SimpleImputer(strategy="median")
train_data[numeric_features] = num_imputer.fit_transform(train_data[numeric_features])
val_data[numeric_features] = num_imputer.transform(val_data[numeric_features])
test_data[numeric_features] = num_imputer.transform(test_data[numeric_features])

C:\Users\X421IA\AppData\Local\Temp\ipykernel_26308\2021079800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[numeric_features] = num_imputer.fit_transform(train_data[numeric_features])
C:\Users\X421IA\AppData\Local\Temp\ipykernel_26308\2021079800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_data[numeric_features] = num_imputer.transform(val_data[numeric_features])
C:\Users\X421IA\AppData\Local\Temp\ipykernel_26308\2021079800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[numeric_features] = num_imputer.transform(test_data[numeric_features])

In [22]:
cat_imputer = SimpleImputer(strategy="most_frequent")

train_data[["surface"]] = cat_imputer.fit_transform(train_data[["surface"]])
val_data[["surface"]] = cat_imputer.transform(val_data[["surface"]])
test_data[["surface"]] = cat_imputer.transform(test_data[["surface"]])

C:\Users\X421IA\AppData\Local\Temp\ipykernel_26308\3314849990.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data[["surface"]] = cat_imputer.fit_transform(train_data[["surface"]])
C:\Users\X421IA\AppData\Local\Temp\ipykernel_26308\3314849990.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_data[["surface"]] = cat_imputer.transform(val_data[["surface"]])
C:\Users\X421IA\AppData\Local\Temp\ipykernel_26308\3314849990.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data[["surface"]] = cat_imputer.transform(test_data[["surface"]])

In [23]:
print(train_data.isna().sum())
print(val_data.isna().sum())
print(test_data.isna().sum())

year             0
rank_diff        0
age_diff         0
height_diff      0
cluster_diff     0
elo_diff         0
surface          0
tourney_level    0
target           0
dtype: int64
year             0
rank_diff        0
age_diff         0
height_diff      0
cluster_diff     0
elo_diff         0
surface          0
tourney_level    0
target           0
dtype: int64
year             0
rank_diff        0
age_diff         0
height_diff      0
cluster_diff     0
elo_diff         0
surface          0
tourney_level    0
target           0
dtype: int64

#### Encoding and Scaler

In [24]:
categorical_features = ["surface", "tourney_level"]
numeric_features = ["rank_diff", "age_diff",
                    "height_diff", "cluster_diff", "elo_diff"]

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ],
    remainder="drop"  # drop any other columns
)

In [26]:
X_train = train_data.drop(columns=["target"])
y_train = train_data["target"]

X_val = val_data.drop(columns=["target"])
y_val = val_data["target"]

X_test = test_data.drop(columns=["target"])
y_test = test_data["target"]

X_train_processed = preprocessor.fit_transform(X_train)
X_val_processed = preprocessor.transform(X_val)
X_test_processed = preprocessor.transform(X_test)

#### Return to Data Frame

In [27]:
feature_names = preprocessor.get_feature_names_out()

X_train_df = pd.DataFrame(X_train_processed, columns=feature_names)
X_val_df = pd.DataFrame(X_val_processed, columns=feature_names)
X_test_df = pd.DataFrame(X_test_processed, columns=feature_names)

## Train Logistic Regression With ELO Surface

In [28]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(max_iter=1000, random_state=42)
log_reg.fit(X_train_df, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [29]:
from sklearn.metrics import roc_auc_score, accuracy_score

val_probs = log_reg.predict_proba(X_val_df)[:, 1]
val_auc = roc_auc_score(y_val, val_probs)

print("Validation ROC-AUC with ELO:", val_auc)

Validation ROC-AUC with ELO: 0.7034749460420117

### Evaluate on Test

In [30]:
y_test_pred = log_reg.predict(X_test_df)
y_test_proba = log_reg.predict_proba(X_test_df)[:, 1]

test_acc = accuracy_score(y_test, y_test_pred)
test_auc = roc_auc_score(y_test, y_test_proba)

print(f"Test Accuracy (2024): {test_acc:.4f}")
print(f"Test ROC-AUC (2024): {test_auc:.4f}")

Test Accuracy (2024): 0.6466
Test ROC-AUC (2024): 0.7107

## Train Neural Network with ELO

In [31]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cpu

In [32]:
X_train_t = torch.tensor(X_train_df.values, dtype=torch.float32)
y_train_t = torch.tensor(y_train.to_numpy(), dtype=torch.float32)

X_val_t = torch.tensor(X_val_df.values, dtype=torch.float32)
y_val_t = torch.tensor(y_val.to_numpy(), dtype=torch.float32)

X_test_t = torch.tensor(X_test_df.values, dtype=torch.float32)
y_test_t = torch.tensor(y_test.to_numpy(), dtype=torch.float32)

print(X_train_t.shape, y_train_t.shape)

torch.Size([25630, 13]) torch.Size([25630])

#### Datasets and DataLoaders

In [33]:
from src.dataset import MatchDataset
from torch.utils.data import DataLoader

BATCH_SIZE = 64

train_dataset = MatchDataset(X_train_t, y_train_t)
val_dataset = MatchDataset(X_val_t, y_val_t)
test_dataset = MatchDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

In [34]:
from src.models import MatchOutcomeNN

input_dim = X_train_df.shape[1]
model = MatchOutcomeNN(input_dim).to(device)

model

MatchOutcomeNN(
  (network): Sequential(
    (0): Linear(in_features=13, out_features=32, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=32, out_features=16, bias=True)
    (4): ReLU()
    (5): Dropout(p=0.2, inplace=False)
    (6): Linear(in_features=16, out_features=1, bias=True)
  )
)

#### Loss function and optimizer

In [35]:
import torch.nn as nn

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

### Training

In [36]:
from src.train import train_one_epoch, evaluate

EPOCHS = 20
best_val_auc = 0.0
best_state_dict = None

In [37]:
for epoch in range(1, EPOCHS + 1):
    train_loss = train_one_epoch(     # train using training data (2018-2022)
        model, 
        train_loader,
        optimizer, 
        criterion, 
        device)
    
    val_acc, val_auc, *_, = evaluate(      # evaluate on validation data (2023)
        model, 
        val_loader, 
        device)
    
    print(
        f"Epoch {epoch:02d} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Acc: {val_acc:.4f} | "
        f"Val AUC: {val_auc:.4f}"
    )

    # Save best model (by AUC)
    if val_auc > best_val_auc:
        best_val_auc = val_auc
        best_state_dict = model.state_dict()

Epoch 01 | Train Loss: 0.6459 | Val Acc: 0.6386 | Val AUC: 0.7032
Epoch 02 | Train Loss: 0.6299 | Val Acc: 0.6397 | Val AUC: 0.7054
Epoch 03 | Train Loss: 0.6275 | Val Acc: 0.6403 | Val AUC: 0.7056
Epoch 04 | Train Loss: 0.6275 | Val Acc: 0.6408 | Val AUC: 0.7053
Epoch 05 | Train Loss: 0.6247 | Val Acc: 0.6390 | Val AUC: 0.7056
Epoch 06 | Train Loss: 0.6248 | Val Acc: 0.6427 | Val AUC: 0.7070
Epoch 07 | Train Loss: 0.6233 | Val Acc: 0.6437 | Val AUC: 0.7070
Epoch 08 | Train Loss: 0.6219 | Val Acc: 0.6427 | Val AUC: 0.7065
Epoch 09 | Train Loss: 0.6240 | Val Acc: 0.6427 | Val AUC: 0.7062
Epoch 10 | Train Loss: 0.6227 | Val Acc: 0.6432 | Val AUC: 0.7064
Epoch 11 | Train Loss: 0.6226 | Val Acc: 0.6428 | Val AUC: 0.7070
Epoch 12 | Train Loss: 0.6225 | Val Acc: 0.6452 | Val AUC: 0.7077
Epoch 13 | Train Loss: 0.6222 | Val Acc: 0.6427 | Val AUC: 0.7076
Epoch 14 | Train Loss: 0.6221 | Val Acc: 0.6448 | Val AUC: 0.7075
Epoch 15 | Train Loss: 0.6210 | Val Acc: 0.6445 | Val AUC: 0.7072
Epoch 16 | Train Loss: 0.6216 | Val Acc: 0.6433 | Val AUC: 0.7078
Epoch 17 | Train Loss: 0.6213 | Val Acc: 0.6457 | Val AUC: 0.7081
Epoch 18 | Train Loss: 0.6213 | Val Acc: 0.6448 | Val AUC: 0.7081
Epoch 19 | Train Loss: 0.6201 | Val Acc: 0.6458 | Val AUC: 0.7085
Epoch 20 | Train Loss: 0.6197 | Val Acc: 0.6448 | Val AUC: 0.7080

### Load Best Model

In [38]:
model.load_state_dict(best_state_dict)
print("Best validation AUC:", best_val_auc)

Best validation AUC: 0.7085081462991617

### Evaluate on Test set

In [39]:
test_acc, test_auc, *_ = evaluate(
    model,
    test_loader,
    device
)

print(f"Neural Network Test Accuracy (2024): {test_acc:.4f}")
print(f"Neural Network Test ROC-AUC (2024): {test_auc:.4f}")

Neural Network Test Accuracy (2024): 0.6481
Neural Network Test ROC-AUC (2024): 0.7116

## Comparison

#### Logistic Regression

| Feature Setup        | Test Accuracy | Test ROC-AUC |
| -------------------- | ------------- | ------------ |
| Global ELO           | 0.6466        | **0.7118**   |
| Surface-specific ELO | 0.6466        | 0.7107       |

---

#### Neural Network

| Feature Setup        | Test Accuracy | Test ROC-AUC |
| -------------------- | ------------- | ------------ |
| Global ELO           | 0.6484        | **0.7129**   |
| Surface-specific ELO | 0.6481        | 0.7116       |

Surface ELO is slightly worse. Global ELO is the better and more stable configuration. This tells us something important:

* Your dataset size (2018–2024) likely isn't large enough per surface
* Global ELO already captures most of the strength signal